project:
  type: website
  output-dir: docs

website:
  title: "maria cecília macedo"
  navbar:
    left:
      - href: experiencia.qmd
        text: experiência
      - href: projetos.qmd
        text: projetos
      - href: atividades.qmd
        text: atividades
      
  
  favicon: tubarao_dentuco.jpg

format:
  html:
    #theme: superhero (original - fundo azul)
    theme: cosmo #(branco)
    #theme: flatly
    #theme: minty
    #theme: simplex
    #theme: superhero
    css: styles.css
    toc: true
    lang: pt

editor: source